// // This file is used to create dummy data for the database

const categories = {
  'Manage Datasets': [
    'Create a new dataset',
    'Rename an existing dataset',
    'Make PI owner of dataset',
    'Add/Edit Permissions',
    'Add/Edit Permissions - Add User Permissions',
    'Add/Edit Permissions - Add Team Permissions',
    'Add/Edit Subtitle',
    'Add/Edit Subtitle - Get Subtitle',
    'Add/Edit Readme',
    'Add/Edit Readme - Get Readme',
    'Add/Edit Readme - Parse Readme',
    'Upload a Banner Image',
    'Upload a Banner Image - Get Banner Image',
    'Upload a Banner Image - Importing Banner Image',
    'Upload a Banner Image - Size',
    'Add/Edit Tags',
    'Add/Edit Tags - Get Tags',
    'Assign a License',
    'Assign a License - Get License',
    'Upload Local Dataset',
    'Upload Local Dataset - Size',
    'Upload Local Dataset - Name - Size',
    'Upload Local Dataset - Number of Folders',
    'Upload Local Dataset - Name - Number of Folders',
    'Upload Local Dataset - Number of Files',
    'Upload Local Dataset - Name - Number of Files',
    'Change Dataset Status',
    'Change Dataset Status - Get Dataset Status',
  ],
  'Prepare Metadata': [
    'Add Airtable account',
    'Add DDD',
    'Create Submission',
    'Create dataset_description',
    'samples',
    'samples - Generate',
    'samples - Generate - Local',
    'samples - Generate - Pennsieve',
    'samples - Existing',
    'samples - Existing - Local',
    'samples - Existing - Pennsieve',
    'submission',
    'submission - Generate',
    'submission - Generate - Local',
    'submission - Generate - Pennsieve',
    'submission - Existing',
    'submission - Existing - Local',
    'submission - Existing - Pennsieve',
    'dataset_description',
    'dataset_description - Generate',
    'dataset_description - Generate - Local',
    'dataset_description - Generate - Pennsieve',
    'dataset_description - Existing',
    'dataset_description - Existing - Local',
    'dataset_description - Existing - Pennsieve',
    'subjects',
    'subjects - Generate',
    'subjects - Generate - Local',
    'subjects - Generate - Pennsieve',
    'subjects - Existing',
    'subjects - Existing - Local',
    'subjects - Existing - Pennsieve',
    'readme',
    'readme - Generate',
    'readme - Generate - Local',
    'readme - Generate - Pennsieve',
    'readme - Existing',
    'readme - Existing - Local',
    'readme - Existing - Pennsieve',
    'changes',
    'changes - Generate',
    'changes - Generate - Local',
    'changes - Generate - Pennsieve',
    'changes - Existing',
    'changes - Existing - Local',
    'changes - Existing - Pennsieve',
    'manifest',
    'manifest - Generate',
    'manifest - Generate - Local',
    'manifest - Generate - Pennsieve',
    'manifest - Existing',
    'manifest - Existing - Local',
    'manifest - Existing - Pennsieve', 
  ],
  'Download Template': [
    'manifest.xlsx',
    'dataset_description.xlsx',
    'subjects.xlsx',
    'samples.xlsx',
    'submission.xlsx',
  ],
  'Prepare Datasets': [
        'Organize dataset',
        'Organize dataset - Existing',
        'Organize dataset - Existing - Pennsieve',
        'Organize dataset - Existing - Local',
        'Organize dataset - Existing - Saved',
        'Organize dataset - Step 3',
        'Organize dataset - Step 3 - Import',
        'Organize dataset - Step 3 - Import - File',
        'Organize dataset - Step 3 - Import - File - Local',
        'Organize dataset - Step 3 - Import - File - Saved',
        'Organize dataset - Step 3 - Import - File - Pennsieve',
        'Organize dataset - Step 3 - Import - File - New',
        'Organize dataset - Step 3 - Import - Folder',
        'Organize dataset - Step 3 - Import - Folder - Local',
        'Organize dataset - Step 3 - Import - Folder - Saved',
        'Organize dataset - Step 3 - Import - Folder - Pennsieve',
        'Organize dataset - Step 3 - Import - Folder - New',
        'Organize dataset - Step 3 - Add - Folder',
        'Organize dataset - Step 3 - Add - Folder - Local',
        'Organize dataset - Step 3 - Add - Folder - Saved',
        'Organize dataset - Step 3 - Add - Folder - Pennsieve',
        'Organize dataset - Step 3 - Add - Folder - New',
        'Organize dataset - Step 4',
        'Organize dataset - Step 4 - Import',
        'Organize dataset - Step 4 - Import - subjects - Local',
        'Organize dataset - Step 4 - Import - subjects - Local - Saved',
        'Organize dataset - Step 4 - Import - subjects - Local - Pennsieve',
        'Organize dataset - Step 4 - Import - subjects - Local - Local',
        'Organize dataset - Step 4 - Import - subjects - Local - New',
        'Organize dataset - Step 4 - Import - subjects - Pennsieve',
        'Organize dataset - Step 4 - Import - subjects - Pennsieve - Saved',
        'Organize dataset - Step 4 - Import - subjects - Pennsieve - Pennsieve',
        'Organize dataset - Step 4 - Import - subjects - Pennsieve - Local',
        'Organize dataset - Step 4 - Import - subjects - Pennsieve - New',
        'Organize dataset - Step 4 - Import - samples - Local',
        'Organize dataset - Step 4 - Import - samples - Local - Saved',
        'Organize dataset - Step 4 - Import - samples - Local - Pennsieve',
        'Organize dataset - Step 4 - Import - samples - Local - Local',
        'Organize dataset - Step 4 - Import - samples - Local - New',
        'Organize dataset - Step 4 - Import - samples - Pennsieve',
        'Organize dataset - Step 4 - Import - samples - Pennsieve - Saved',
        'Organize dataset - Step 4 - Import - samples - Pennsieve - Pennsieve',
        'Organize dataset - Step 4 - Import - samples - Pennsieve - Local',
        'Organize dataset - Step 4 - Import - samples - Pennsieve - New',
        'Organize dataset - Step 4 - Import - submission - Local',
        'Organize dataset - Step 4 - Import - submission - Local - Saved',
        'Organize dataset - Step 4 - Import - submission - Local - Pennsieve',
        'Organize dataset - Step 4 - Import - submission - Local - Local',
        'Organize dataset - Step 4 - Import - submission - Local - New',
        'Organize dataset - Step 4 - Import - submission - Pennsieve',
        'Organize dataset - Step 4 - Import - submission - Pennsieve - Saved',
        'Organize dataset - Step 4 - Import - submission - Pennsieve - Pennsieve',
        'Organize dataset - Step 4 - Import - submission - Pennsieve - Local',
        'Organize dataset - Step 4 - Import - submission - Pennsieve - New',
        'Organize dataset - Step 4 - Import - dataset_description - Local',
        'Organize dataset - Step 4 - Import - dataset_description - Local - Saved',
        'Organize dataset - Step 4 - Import - dataset_description - Local - Pennsieve',
        'Organize dataset - Step 4 - Import - dataset_description - Local - Local',
        'Organize dataset - Step 4 - Import - dataset_description - Local - New',
        'Organize dataset - Step 4 - Import - dataset_description - Pennsieve',
        'Organize dataset - Step 4 - Import - dataset_description - Pennsieve - Saved',
        'Organize dataset - Step 4 - Import - dataset_description - Pennsieve - Pennsieve',
        'Organize dataset - Step 4 - Import - dataset_description - Pennsieve - Local',
        'Organize dataset - Step 4 - Import - dataset_description - Pennsieve - New',
        'Organize dataset - Step 4 - Import - README - Local',
        'Organize dataset - Step 4 - Import - README - Local - Saved',
        'Organize dataset - Step 4 - Import - README - Local - Pennsieve',
        'Organize dataset - Step 4 - Import - README - Local - Local',
        'Organize dataset - Step 4 - Import - README - Local - New',
        'Organize dataset - Step 4 - Import - README - Pennsieve',
        'Organize dataset - Step 4 - Import - README - Pennsieve - Saved',
        'Organize dataset - Step 4 - Import - README - Pennsieve - Pennsieve',
        'Organize dataset - Step 4 - Import - README - Pennsieve - Local',
        'Organize dataset - Step 4 - Import - README - Pennsieve - New',
        'Organize dataset - Step 4 - Import - CHANGES - Local',
        'Organize dataset - Step 4 - Import - CHANGES - Local - Saved',
        'Organize dataset - Step 4 - Import - CHANGES - Local - Pennsieve',
        'Organize dataset - Step 4 - Import - CHANGES - Local - Local',
        'Organize dataset - Step 4 - Import - CHANGES - Local - New',
        'Organize dataset - Step 4 - Import - CHANGES - Pennsieve',
        'Organize dataset - Step 4 - Import - CHANGES - Pennsieve - Saved',
        'Organize dataset - Step 4 - Import - CHANGES - Pennsieve - Pennsieve',
        'Organize dataset - Step 4 - Import - CHANGES - Pennsieve - Local',
        'Organize dataset - Step 4 - Import - CHANGES - Pennsieve - New',
        'Organize dataset - Step 4 - Import - CHANGES - Pennsieve',
        'Organize dataset - Step 7',
        'Organize dataset - Step 7 - Generate',
        'Organize dataset - Step 7 - Generate - Dataset',
        'Organize dataset - Step 7 - Generate - Dataset - Pennsieve',
        'Organize dataset - Step 7 - Generate - Dataset - Pennsieve - Local',
        'Organize dataset - Step 7 - Generate - Dataset - Pennsieve - Saved',
        'Organize dataset - Step 7 - Generate - Dataset - Pennsieve - New',
        'Organize dataset - Step 7 - Generate - Dataset - Pennsieve - Pennsieve',
        'Organize dataset - Step 7 - Generate - Dataset - Local',
        'Organize dataset - Step 7 - Generate - Dataset - Local - Local',
        'Organize dataset - Step 7 - Generate - Dataset - Local - Saved',
        'Organize dataset - Step 7 - Generate - Dataset - Local - New',
        'Organize dataset - Step 7 - Generate - Dataset - Local - Pennsieve',
        'Organize dataset - Step 7 - Generate - Dataset - Size',
        'Organize dataset - Step 7 - Generate - Dataset - Pennsieve - Size',
        'Organize dataset - Step 7 - Generate - Dataset - Local - Size',
        'Organize dataset - Step 7 - Generate - Dataset - Number of Files',
        'Organize dataset - Step 7 - Generate - Dataset - Pennsieve - Number of Files',
        'Organize dataset - Step 7 - Generate - Dataset - Local - Number of Files',
        'Organize dataset - Step 7 - Generate - Manifest',
        'Organize dataset - Step 7 - Generate - Manifest - Pennsieve',
        'Organize dataset - Step 7 - Generate - Manifest - Local',
        'Organize dataset - Step 7 - Generate - Dataset - Pennsieve - Create a duplicate',
        'Organize dataset - Step 7 - Generate - Dataset - Pennsieve - Replace',
        'Organize dataset - Step 7 - Generate - Dataset - Pennsieve - Merge',
        'Organize dataset - Step 7 - Generate - Dataset - Pennsieve - Skip',
  ],
  'Disseminate Datasets': [
    'Show current dataset permission',
    'Show current dataset status',
    'Pre-publishing Review - Integrate ORCID iD',
    'Pre-publishing Review - Get Excluded Files',
    'Pre-publishing Review - Get Metadata Files',
    'Pre-publishing Review - Update excluded files',
    'Pre-publishing Review - Publish',
    'Pre-publishing Review - Submit dataset',
    'Pre-publishing Review - Withdraw dataset',
    'Pre-publishing Review - Fetch Pre-publishing Checklist Statuses',
    "Pre-publishing Review - Determine User's Dataset Role",
    "Pre-publishing Review - Show publishing status",
    'Share with Curation Team',
    "Share with Curation Team - Remove Consortium's Team Permissions",
    "Share with Curation Team - Give Consortium Team Permissions",
    "Share with Curation Team - Change Dataset Status to Work In Progress",
    "Share with Curation Team - Change Dataset Status to Ready for Curation",
    'Share with Consortium',
    'Share with Consortium - Removed Team Permissions SPARC Consortium',
    'Share with Consortium - Add Team Permissions SPARC Consortium',
    'Share with Consortium - Curated & Awaiting PI Approval',
    'Share with Consortium - Change Dataset Status to Under Embargo',
    'Pre-publishing Review',
  ]
}

const success = [true, false]

const sodaVersion = ['11.0.0', '10.0.0', '9.0.0', '8.0.0', '7.0.0']


const generateRandomNumber = (min, max) => {
  return Math.floor(Math.random() * (max - min + 1)) + min
}

console.log(generateRandomNumber(0, 1));
